### ISSUE TITLE
我终于进来了啦啦啦！

### ISSUE THREAD

**Issue by niwakoki** [qyxf/qyxf.github.io#1]
啦啦啦啦啦！我是大一小萌### 新啦啦啦啦啦啦啦！
啦啦啦啦啦！lalalalalalalal
lalalalalalalala
ららららららああああああ大家都在发大家都在发大家都在发大家都在发皮卡丘
(灬°ω°灬) (灬°ω°灬) (灬°ω°灬) (灬°ω°灬) (灬°ω°灬) (o°ω°o)(o´ω`o)ﾉヾ(❀^ω^)ﾉﾞ(*•ω•)ヾ(•ω•`。)

**Comment by niwakoki** [comment]
忘记加label了
forgot to label

**Comment by xjtu-blacksmith** [comment]
双语好评！
