### ISSUE TITLE
颜色的一点建议

### ISSUE THREAD

**Issue by siyuanwu99** [qyxf/qyxf.github.io#10]
网站底色使用的是黑色333333，文字部分底色是白色fbfbfb，感觉对比有些过于强烈

**Comment by xjtu-blacksmith** [comment]
目前希望体现出来的效果类似于「夜间风格」，在暗背景上铺一张白纸，可以使读者集中在中间内容上，并有阅读的感受。

CSDN 上的一些博客，以及部分程序文档网站（如[这个](https://www.reactjscn.com/)与[这个](https://www.parceljs.cn/)）都是类似做法，只不过我们的正文部分（`section` 标签）没有将页面宽度填满而已。
