### ISSUE TITLE
我要贡献 | 钱院学辅信息站 - qyxf.site

### ISSUE THREAD

**Issue by xjtu-blacksmith** [qyxf/qyxf.github.io#18]
https://qyxf.site/contribution 

 钱院学辅信息站

**Comment by xjtu-blacksmith** [comment]
请登录 [GitHub](https://github.com) 后在此留下您的**宝贵意见**！如对 GitHub 感到陌生，欢迎阅读我们的[入门教程](https://qyxf.site/technique/git-github)，走进开源新世界！

钱院学辅首页：https://qyxf.site

**Comment by siyuanwu99** [comment]
请问相关课程笔记（手写，goodnote格式）如何贡献

**Comment by xjtu-blacksmith** [comment]
> @edmundwsy
> 请问相关课程笔记（手写，goodnote格式）如何贡献

协商之后，如果认为这样的手写笔记有必要重新排版，则会考虑从头整理；若认为其本身格式、资源引用等已经合规、美观，则会直接在[钱院学辅·书库](/BookHub)发布。
