### ISSUE TITLE
网站的外观不够美观，稍显老气，使用也不甚便捷

### ISSUE THREAD

**Issue by merak0514** [qyxf/qyxf.github.io#28]
* 整体：设计偏向于十/二十年前的bbs风格。
* 大多数内容没有必要的仅仅占据网页的中心位置，就好像用电脑打开一个网页的手机端似的。
* 导航栏不明显，目前放在页面中心的位置，同时没有固定导航栏，导致切换页面/上下滑动时若需使用导航栏还要划到中间。（关于导航栏应该是只需要写一个单独的div，然后设置为fix，就可以始终保持在页面最上方悬空。）参考知乎以及大多数网站，导航栏固定位置，使用方便。
* 在《推送一览》中的名字部分配色混乱，可以参考[nipponcolors](nipponcolors.com)中的配色（甚至随便抄一行都行）。
* 网页最上方的header实在很丑，看起来就像广告栏一样。

网站里的东西还挺全的，我认为钱院学辅搭建这个网站是一个非常棒的尝试。以上是比较直接的批评，以下给出可能可以参考的解决方案：

* 比较美观且使用简单的设计可以参考一些ssr网站（例：[ssrcloud.org](ssrcloud.org)），这些站长使用的是几乎相同的模板，但做出来的效果都不错。
* 页面背景的动效有不少现成的成功demo，开源的也有不少，可以参考[这个网站](https://juejin.im/post/5cc089eae51d456e7d189f9d)。

**Comment by xjtu-blacksmith** [comment]
感谢提出 issue（本站常年无人关注）。

关于您的建议，我以本站搭建的历史经验来回复：

1. 您所说的「十/二十年前 BBS 风格」，我无法推知（因为十/二十年前我还没有使用过 BBS），我猜测可能的原因是：我是按「排版模式」来组织页面的，所以对除了正文界面以外的内容几乎没有设计（或者说，几乎没有）。可能的原因有几个：
    - 我没有专门研究过网页布局的风格，并且学排版在学网页设计之前；所以我一直的理想网页是「内容占绝对优势」。
    - 页面现在用的架构基本上和原来用的 [Leap Day](https://github.com/pages-themes/leap-day) 没有差别，也许是我长期只看此种布局方式，视界太窄了。
    - 此外，我的技术水平也有限，因此没有产生过优化页面布局的打算。

    您在此处的建议算一条。之前与我在带的一些学弟们交流时，他们也提出了其他一些方面的建议，我认为可以作为未来页面布局调整的参考方向。

2. 关于页面中心（`section` 标签）比例「夸张」的情况，一方面是直接继承自 Leap Day（前段时间我稍微调宽了些，但模式没有本质改变），另一方面也还是我的那种「排版式」偏好，我自己一直觉得效果较好。我认为比例可能是主要问题，模式本身倒不必纠结；很多个人博客都采用这种把两边留空的方式（这会儿随便找了一个：<https://ibruce.info>；NexT 系的很多主题，也不过是多出了固定一栏），我觉得这倒是算一种新尝试，不在您上一个提议所言的「十/二十年前 BBS 风格」之列。
3. 关于导航栏：原用的 Leap Day 主题中，导航栏是 fix（悬空）在视口顶部的，但是当时为了处理动态目录的跳转会因此出现问题（覆盖在内容之上，占去一点高度，使得标题跳转位置计算常常有误），就改成固定的了。另一方面，我的确发现：在移动端访问占主（这个我比较清楚）、本站功能有限的前提下，这个导航栏基本上属于**摆设**，对新访客而言要么会被点一次，要么不会用到。所以这一块目前问题确实存在，只是改进需求不足、暂时如此。从您的建议来看，需求还是存在的；我会与组内其他同学讨论这件事情。
4. 关于名牌配色：我是将 <https://shields.io> 下几个默认关键字色彩（`red`、`blue` 之类）渐暗后的效果直接移植过来的——你可以看出来，现在的这些 `span` 标签，和 GitHub 各 README 界面上的标牌几乎一模一样。我自己的确不会调色，每次要用多种色彩时我都是很苦恼。关于您（还有 @edmundwsy）建议的 Nippon Colors，我浏览了一下列表，但没有明白这一套色表的独特之处（或优势）何在，希望您进一步说明。（我之前想的是，配色让钱院各专业班级派~~美术课~~代表讨论、分配，但是这样的事情恐怕也很难组织起来。）
5. Header 确实是丑，不得不说它和「澳门赌场」有几分相似（……）我会列入改进清单。

再是关于您提出的两条可能的解决方案：

1. 对 ssrcloud（不包括其它机场）的主题，我本人（不代表其他及后继维护者）的看法是：功能强大，但不适合显示大段正文内容。前者本站暂用不上；后者是本站目前比较关注的问题。——当然，我得承认，我的关注点很多时候比较**狭隘**：过去我上 ssrcloud 的时候，只是反感公告面板那里排版混乱、`padding` 不对劲、个别页面字体大小不均整之类的问题，而没有很特别留意页面风格。
2. 感谢您推荐的这些动态效果库，我会建议组内的后辈们尝试一下（我自己不敢把站点技术门槛设的太高，担心难以递接，连 JQuery 都不太敢用）；至于背景动态效果，在目前内容为主（且正文背景非透明）、移动端浏览占大头的前提下，可能暂时不会考虑。

过去几个月来的网站改进（样式修补和内容撰写、排版），已经令我这个纯粹的业余人士精疲力竭；我正在督促着组里的同学（全都是计算机相关方向）加紧学习相关内容，让潜力更大、未来发展方向更对口的爱好者来接手此站。

相信您所说的问题在未来会悉数解决。

**Comment by merak0514** [comment]
0. 我认为【内容占绝对优势】恐怕与较为合理的排版布局并不是很矛盾

感谢您详尽的回复，事实上我也并非专业人士，曾经有接触过一些浅显的网页制作，也稍稍谈一些我的看法。
1. 关于section标签，我同意这种风格确有不少可取之处，你所引用的【不如】也确实让人感觉很舒适；细细对比这两个网页，我认为可能是一些细节上的不同带来的观感的差异：
* https://ibruce.info/ 采用半径较大的**圆角**，上/左/右均留出较大的背景，让人感觉比较轻灵；
* 学辅的网站采用小圆角看起来较为死板，同时上面不太美观的header阻挡视线，给人一种作者是想把网页分成3栏，但最后只写了中间一栏的感觉；
* https://ibruce.info/ 的中心栏边缘采用了一些**阴影**，更是衬托了前述轻灵的效果。我注意到目前学辅的网站已经留出了box-shadow的attribute，应该修改一部分参数能较快的实现。
以上圆角与阴影的问题我认为应该不算困难，我在自己网页尝试了一下，应该能有一部分观感的提升。事实上，我说到的在背景加入一些适当的动效，也是希望改善目前死板单调的感觉。（但动效比较难搞，并且在一个强调内容的网站加入过多可能会诱导访客分神）

2. 关于导航栏问题：可以用一个检测请求header的方式区分移动端和电脑的访问，提供不相同的页面；header的制作整体上（在有绘制好的图的情况下）本身并不复杂，如果不用js大约是**3-4小时**的工作量，建议未来可以考虑完成，特别是在网站功能渐渐复杂的时候。如果说在现有的基础上加以调整，我个人认为可以把目前的2*5的**导航**压缩成1*6/1*5甚至1*4：例如，【关于我们】可以下放，【钱院首页】/【订阅本站】的出现意义不大，在刚开学的时候会有足够数量的新生来读【新生必读】吗？

3. 我个人认为header 与 banner在目前可以完全删去，让网页整体更美观整洁，也能更强调内容。

4. 名牌配色的一大问题是**喧宾夺主**，在一个白蓝黑构成的界面上出现的彩色小块恐怕需要谨慎处理；另一方面，在一个2d设计的网页上，几个**伪3d**的名牌也很抢眼。削弱伪3d的效果可能可以采用**减小圆角**radius来实现；甚至名牌可以直接采用不同字体的链接（例如**斜体**）来代替；推送一览中的标题字体可能可以加大，用字体而非名牌的方式来区别开作者与作品；我之前所说在nipponcolors里面找一些相近的配色也是想弱化这种五颜六色的感觉（比如全部找紫色系的颜色[不一定可行]）。

5. ssrcloud确实bug不少，但除此之外我认为它的排版（在电脑端）是很有可取之处的，两栏式的分布让左边的大目录能快速找到想要阅读的重点内容，整个网站被很有条理的组织起来；但考虑到你说的 [主要访客来自移动端]，那么目前的设计确实可以很好的适配移动端（甚至就是移动端的标准配置）。

我比较不认同因为关注内容而忽略网站的外表。钱院学辅建立这个网站的初衷应该有一部分是希望更多人能关注到这个网站上丰富的资源和对学习生活的帮助，由此，营造一个较为良好的阅读体验恐怕不是一件无意义的事情。同时，若是网站做的比同时期的网站逊色，初次打开的人有可能会因此**质疑**此网站内容的正确性。给访问者留下一个良好的印象能扩大网站的读者，从而也增大潜在的作者群体，形成良性循环。

简单的说：有这么多可以提供资源的网站/群，为什么我要看你的？
给出的回答可以有：我这里有别的地方没有的东西/我的网站比别人的好用。

**Comment by merak0514** [comment]
还有一个关于右侧目录：现在这样鼠标移上去展开的设计在实用性上恐怕不如固定展开。

**Comment by xjtu-blacksmith** [comment]
大概理解您的意思了。

- 您所提的本站与[不如](https://ibruce.info)之细节差异，我是认同的，是很好的建议。
- 导航栏上摆满按钮：主要原因是，这里是这些模块的唯一入口，不太好移走到别的地方。包括您所说的：【关于我们】已经放在首页下方，但链接不太明显，所以多加一个；【钱院首页】能否拿走并不单纯取决于维护者的个人意愿（换位思考一下，社团主管老师现在来看这个网站，可能反而嫌和钱院的联系太少了）；【新生必读】是暑假时设置的。我认为您所说的问题，也许在未来可以通过在页底加上「友情链接」来解决。
- header 与 banner 的去留/实现已经列入未来改进计划中。
- 名牌配色的初衷是区分不同班级；当初是设想以这种标识的方式，鼓励社团内同学参与网站内容撰写。您所言的「喧宾夺主」问题，我能够理解，我想比较好的解决方案是**不让名牌密集出现**，而不是将名牌配色改成同色系使其失去原有意义。「削弱伪 3D效果」是很好的建议，我会在之后有空时尝试一下——目前的样式只是单纯「照抄」[sheilds.io](https://shields.io) 风格，没有关心其属性、兼容性。
- 目录的样式目前是为移动端定制的，在电脑上看确实有所欠缺（图标不明显/太小，需要自行打开）。我想可以把这个内容结合进布局改进的计划中。

另外，关于您提到的「『内容占绝对优势』与排版布局合理不矛盾」、「忽略网站外表」等观点，我想您是误解我的含义了。我提到这些现状，意思是指「目前的关注点主要在内容上」，加上我看网站上一般也比较关注内容，所以没有意识到网站的样式存在着您之前所提的诸多问题——而不是我「明知而不改」。

同时，从您的几个评论之中，我注意到您非常关注网站的**功能**（如各类菜单、插件、布局中的各部分组件等），而本站目前的框架基本上还是继承自 GitHub Pages 的[默认主题系列](https://pages.github.com/themes/)，它们的共同特征恰好是「关注内容、形式简洁」，比如 Leap Day 主题的 README 所提到的（根据你的标准，Leap Day 也不会是一个「好」的主题，但是使用这一主题的网站不在少数）：

> The Leap day theme is intended to make it quick and easy for GitHub Pages users to create their first (or 100th) website. The theme should meet the vast majority of users' needs out of the box, erring on the side of simplicity rather than flexibility, ...

当然，我并不是说我们会死守在这样的「philosophy」上。我不赞同您所言的「初次打开的人有可能会因此质疑此网站内容的正确性」，我觉得您的这种预判有些失实了；在 Geek 圈子以外的很多人看来，像我们这种「二十年前」风格的网站恐怕都有些「新颖」，这并非我的杜撰。（本站不是提供给 Geek 们的，包括本站的维护者也离一般 Geek 的水平或「审美」相差甚远——即使是 Jekyll 这样十分基本的工具，对于新手来说也是很难使用的。）

> 补充一点，您看来比较关注「功能」，而我对「内容格式」或「排版样式」比较在意——比如说我会对您无意间提到的「中文斜体」异常反感，从这一点上您应该能理解我前面反复说的「内容」并不是指文章里面打了什么字、说了什么事。

话说很多，没有和您争论的意思；只是这个小小的项目几个月来一直是我一个人摸黑般地探索，因此在个别问题上（比如本站的定位、样式设计的准则等）我会有些固执，会多说几句。我会把这些问题中的一些修正，另一些则留给后继者来做。

**Comment by xjtu-blacksmith** [comment]
> 还有一个关于右侧目录：现在这样鼠标移上去展开的设计在实用性上恐怕不如固定展开。

补充：目录在左侧。

**Comment by xjtu-blacksmith** [comment]
> 大概理解您的意思了。
> 
> * 您所提的本站与[不如](https://ibruce.info)之细节差异，我是认同的，是很好的建议。
> * 导航栏上摆满按钮：主要原因是，这里是这些模块的唯一入口，不太好移走到别的地方。包括您所说的：【关于我们】已经放在首页下方，但链接不太明显，所以多加一个；【钱院首页】能否拿走并不单纯取决于维护者的个人意愿（换位思考一下，社团主管老师现在来看这个网站，可能反而嫌和钱院的联系太少了）；【新生必读】是暑假时设置的。我认为您所说的问题，也许在未来可以通过在页底加上「友情链接」来解决。
> * header 与 banner 的去留/实现已经列入未来改进计划中。
> * 名牌配色的初衷是区分不同班级；当初是设想以这种标识的方式，鼓励社团内同学参与网站内容撰写。您所言的「喧宾夺主」问题，我能够理解，我想比较好的解决方案是**不让名牌密集出现**，而不是将名牌配色改成同色系使其失去原有意义。「削弱伪 3D效果」是很好的建议，我会在之后有空时尝试一下——目前的样式只是单纯「照抄」[sheilds.io](https://shields.io) 风格，没有关心其属性、兼容性。
> * 目录的样式目前是为移动端定制的，在电脑上看确实有所欠缺（图标不明显/太小，需要自行打开）。我想可以把这个内容结合进布局改进的计划中。
> 
> 另外，关于您提到的「『内容占绝对优势』与排版布局合理不矛盾」、「忽略网站外表」等观点，我想您是误解我的含义了。我提到这些现状，意思是指「目前的关注点主要在内容上」，加上我看网站上一般也比较关注内容，所以没有意识到网站的样式存在着您之前所提的诸多问题——而不是我「明知而不改」。
> 
> 同时，从您的几个评论之中，我注意到您非常关注网站的**功能**（如各类菜单、插件、布局中的各部分组件等），而本站目前的框架基本上还是继承自 GitHub Pages 的[默认主题系列](https://pages.github.com/themes/)，它们的共同特征恰好是「关注内容、形式简洁」，比如 Leap Day 主题的 README 所提到的（根据你的标准，Leap Day 也不会是一个「好」的主题，但是使用这一主题的网站不在少数）：
> 
> > The Leap day theme is intended to make it quick and easy for GitHub Pages users to create their first (or 100th) website. The theme should meet the vast majority of users' needs out of the box, erring on the side of simplicity rather than flexibility, ...
> 
> 当然，我并不是说我们会死守在这样的「philosophy」上。我不赞同您所言的「初次打开的人有可能会因此质疑此网站内容的正确性」，我觉得您的这种预判有些失实了；在 Geek 圈子以外的很多人看来，像我们这种「二十年前」风格的网站恐怕都有些「新颖」，这并非我的杜撰。（本站不是提供给 Geek 们的，包括本站的维护者也离一般 Geek 的水平或「审美」相差甚远——即使是 Jekyll 这样十分基本的工具，对于新手来说也是很难使用的。）
> 
> > 补充一点，您看来比较关注「功能」，而我对「内容格式」或「排版样式」比较在意——比如说我会对您无意间提到的「中文斜体」异常反感，从这一点上您应该能理解我前面反复说的「内容」并不是指文章里面打了什么字、说了什么事。
> 
> 话说很多，没有和您争论的意思；只是这个小小的项目几个月来一直是我一个人摸黑般地探索，因此在个别问题上（比如本站的定位、样式设计的准则等）我会有些固执，会多说几句。我会把这些问题中的一些修正，另一些则留给后继者来做决断。

**Comment by xjtu-blacksmith** [comment]
网站目前已经全部重做。

检查之前您所提若干问题及我的意见，看来我们的分歧主要是在基本布局上。当时网站样式基本上全部手写，没有固定框架，因此您所提意见我认为大多很难实践；目前正文已用 MDUI 的分栏布局全部重做，各项内容均有简便方法嵌入页面中，因此可以做较多改善体验的工作了。

您目前所提意见中，除名牌一项仍然保持原状（样式有轻微改动，目前已经比较契合网站主题）外，其余问题基本上都已解决。如在新的样式中发现其他问题，请您新开 issue。感谢。
